import {
  BaseConverter,
  BitRegister,
  BrowserRuntimeDiagram,
  BorrowCheckerPanel,
  ByteAnatomy,
  ConcurrencyChannels,
  EventLoopSimulator,
  HexColorMixer,
  KafkaPipelineVisualizer,
  MtlsHandshake,
  OwnershipVisualizer,
  PacketJourney,
  RequestTimeline,
  SendSyncExplorer,
  SolidSignalGraph,
  StackFrameVisualizer,
  TanStackDataFlow,
  TokioFutureMachine,
  TrustBoundaryDiagram,
  WasmBoundary,
} from "@millipede/lesson-widgets";
import "@millipede/lesson-widgets/styles.css";

export const lessonComponents = {
  BitRegister,
  BaseConverter,
  ByteAnatomy,
  HexColorMixer,
  KafkaPipelineVisualizer,
  RequestTimeline,
  PacketJourney,
  StackFrameVisualizer,
  BrowserRuntimeDiagram,
  TrustBoundaryDiagram,
  MtlsHandshake,
  EventLoopSimulator,
  WasmBoundary,
  OwnershipVisualizer,
  BorrowCheckerPanel,
  ConcurrencyChannels,
  SendSyncExplorer,
  TokioFutureMachine,
  SolidSignalGraph,
  TanStackDataFlow,
};
